name: AI Code Suggestions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-suggestions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub

      - name: Run AI code suggestion
        id: ai-suggestions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/code_suggestor.py > suggestions.md

      # Show AI suggestions in the Checks section summary
      - name: Show AI suggestions in PR checks
        run: |
          echo "## 🤖 AI Code Suggestions" >> $GITHUB_STEP_SUMMARY
          cat suggestions.md >> $GITHUB_STEP_SUMMARY
